# (c) dbj@dbj.org CC BY SA 3.0
# please be usre to note and understand we have one .env file
# in this same folder
# thus we keep all the env vars for all the container 
# in that one .env file
version: '3'
name: 'sampleapp'
services:
  ###################################
  environprinter:
    build:
      context: ./environprinter
      dockerfile: Dockerfile
    labels:
      environment: ENVIRONMENT=${ENVIRONMENT}
    environment:
      - API_KEY=${API_KEY}
    env_file:
      # keep in mind we can have any file we want here
      # the only requirement is for it to be in the .env file format
      - .env
  ###################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    env_file:
      - .env
  ###################################
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
  ###################################
  noderis:
    build:
      context: ./noderis
      dockerfile: Dockerfile
    ports:
      - "${NODERIS_PORT}:${NODERIS_PORT}"
    env_file:
      - .env
  ###################################
  cluster:
    build:
      context: ./cluster
      dockerfile: Dockerfile
    ports:
      - "${CLUSTER_SLEEP}:${CLUSTER_SLEEP}"
    env_file:
      - .env

# note how we re-use the same and one and only .env for the whole constelation in here
# pay attention to the fact the whole contents of that one single .env file is known
# and available to every container
