# (c) dbj@dbj.org CC BY SA 3.0
version: '3'
name: 'sampleapp'
services:
  environprinter:
    build:
      context: ./environprinter
      dockerfile: Dockerfile
    labels:
      environment: ENVIRONMENT=${ENVIRONMENT}
    environment:
      - API_KEY=${API_KEY}
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend
    env_file:
      - .env
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
